"""add form and submission core tables

Revision ID: 34dbb0492aec
Revises: 6b55cddd2ff4
Create Date: 2026-05-06 08:59:01.404064

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '34dbb0492aec'
down_revision = '6b55cddd2ff4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='draft', nullable=False),
    sa.Column('visibility', sa.String(length=30), server_default='internal', nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('owner_scope_type', sa.String(length=50), server_default='global', nullable=False),
    sa.Column('owner_scope_code', sa.String(length=100), nullable=True),
    sa.Column('owner_scope_name', sa.String(length=255), nullable=True),
    sa.Column('owner_scope_path', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_scope_type', sa.String(length=50), server_default='global', nullable=False),
    sa.Column('target_scope_code', sa.String(length=100), nullable=True),
    sa.Column('target_scope_name', sa.String(length=255), nullable=True),
    sa.Column('target_scope_path', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('access_policy_key', sa.String(length=100), server_default='form.default', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_by_uuid', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_by_uuid', sa.String(length=36), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by_uuid', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('uuid')
    )
    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.create_index('ix_forms_deleted_at', ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_forms_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forms_owner_scope_type'), ['owner_scope_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_forms_owner_scope_code'), ['owner_scope_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_forms_target_scope_type'), ['target_scope_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_forms_target_scope_code'), ['target_scope_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_forms_access_policy_key'), ['access_policy_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_forms_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_forms_visibility'), ['visibility'], unique=False)

    op.create_table('form_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('version_label', sa.String(length=100), nullable=True),
    sa.Column('schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('validation_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('submission_contract', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scope_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('access_policy_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='draft', nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_by_uuid', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_by_uuid', sa.String(length=36), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by_uuid', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('form_id', 'version_number', name='uq_form_versions_form_id_version_number'),
    sa.UniqueConstraint('uuid')
    )
    with op.batch_alter_table('form_versions', schema=None) as batch_op:
        batch_op.create_index('ix_form_versions_deleted_at', ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_form_versions_form_id'), ['form_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_form_versions_is_published'), ['is_published'], unique=False)
        batch_op.create_index(batch_op.f('ix_form_versions_status'), ['status'], unique=False)

    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('submission_number', sa.String(length=100), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('form_version_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='draft', nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validation_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('submitted_by_uuid', sa.String(length=36), nullable=True),
    sa.Column('owner_scope_type', sa.String(length=50), server_default='global', nullable=False),
    sa.Column('owner_scope_code', sa.String(length=100), nullable=True),
    sa.Column('owner_scope_name', sa.String(length=255), nullable=True),
    sa.Column('owner_scope_path', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('subject_type', sa.String(length=50), nullable=True),
    sa.Column('subject_ref_id', sa.Integer(), nullable=True),
    sa.Column('subject_ref_uuid', sa.String(length=36), nullable=True),
    sa.Column('subject_ref_code', sa.String(length=100), nullable=True),
    sa.Column('subject_ref_name', sa.String(length=255), nullable=True),
    sa.Column('access_policy_key', sa.String(length=100), server_default='submission.default', nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_ref', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_by_uuid', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_by_uuid', sa.String(length=36), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by_uuid', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ),
    sa.ForeignKeyConstraint(['form_version_id'], ['form_versions.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_number'),
    sa.UniqueConstraint('uuid')
    )
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.create_index('ix_submissions_deleted_at', ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_form_id'), ['form_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_form_version_id'), ['form_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_owner_scope_type'), ['owner_scope_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_owner_scope_code'), ['owner_scope_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_subject_type'), ['subject_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_subject_ref_id'), ['subject_ref_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_subject_ref_uuid'), ['subject_ref_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_subject_ref_code'), ['subject_ref_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_access_policy_key'), ['access_policy_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_submitted_at'), ['submitted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_submitted_by'), ['submitted_by'], unique=False)

    op.create_table('submission_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_user_uuid', sa.String(length=36), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_by_uuid', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_by_uuid', sa.String(length=36), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by_uuid', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    with op.batch_alter_table('submission_events', schema=None) as batch_op:
        batch_op.create_index('ix_submission_events_deleted_at', ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_submission_events_event_at'), ['event_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_submission_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_submission_events_submission_id'), ['submission_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submission_events_submission_id'))
        batch_op.drop_index(batch_op.f('ix_submission_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_submission_events_event_at'))
        batch_op.drop_index('ix_submission_events_deleted_at')

    op.drop_table('submission_events')
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submissions_submitted_by'))
        batch_op.drop_index(batch_op.f('ix_submissions_submitted_at'))
        batch_op.drop_index(batch_op.f('ix_submissions_status'))
        batch_op.drop_index(batch_op.f('ix_submissions_source_type'))
        batch_op.drop_index(batch_op.f('ix_submissions_access_policy_key'))
        batch_op.drop_index(batch_op.f('ix_submissions_subject_ref_code'))
        batch_op.drop_index(batch_op.f('ix_submissions_subject_ref_uuid'))
        batch_op.drop_index(batch_op.f('ix_submissions_subject_ref_id'))
        batch_op.drop_index(batch_op.f('ix_submissions_subject_type'))
        batch_op.drop_index(batch_op.f('ix_submissions_owner_scope_code'))
        batch_op.drop_index(batch_op.f('ix_submissions_owner_scope_type'))
        batch_op.drop_index(batch_op.f('ix_submissions_form_version_id'))
        batch_op.drop_index(batch_op.f('ix_submissions_form_id'))
        batch_op.drop_index('ix_submissions_deleted_at')

    op.drop_table('submissions')
    with op.batch_alter_table('form_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_form_versions_status'))
        batch_op.drop_index(batch_op.f('ix_form_versions_is_published'))
        batch_op.drop_index(batch_op.f('ix_form_versions_form_id'))
        batch_op.drop_index('ix_form_versions_deleted_at')

    op.drop_table('form_versions')
    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forms_visibility'))
        batch_op.drop_index(batch_op.f('ix_forms_status'))
        batch_op.drop_index(batch_op.f('ix_forms_access_policy_key'))
        batch_op.drop_index(batch_op.f('ix_forms_target_scope_code'))
        batch_op.drop_index(batch_op.f('ix_forms_target_scope_type'))
        batch_op.drop_index(batch_op.f('ix_forms_owner_scope_code'))
        batch_op.drop_index(batch_op.f('ix_forms_owner_scope_type'))
        batch_op.drop_index(batch_op.f('ix_forms_owner_user_id'))
        batch_op.drop_index('ix_forms_deleted_at')

    op.drop_table('forms')
    # ### end Alembic commands ###
