"""add reporting periods

Revision ID: 7d61714f1651
Revises: 34dbb0492aec
Create Date: 2026-05-07 06:12:20.395795

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7d61714f1651'
down_revision = '34dbb0492aec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reporting_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('period_type', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('input_opens_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('input_closes_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.String(length=30), server_default='draft', nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_by_uuid', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_by_uuid', sa.String(length=36), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by_uuid', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('uuid')
    )
    with op.batch_alter_table('reporting_periods', schema=None) as batch_op:
        batch_op.create_index('ix_reporting_periods_deleted_at', ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reporting_periods_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_reporting_periods_period_type'), ['period_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_reporting_periods_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_reporting_periods_year'), ['year'], unique=False)

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        # Tambahkan nullable lebih dulu agar aman jika tabel submissions sudah berisi data.
        batch_op.add_column(sa.Column('reporting_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reporting_period_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_submissions_reporting_period_id'), ['reporting_period_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_reporting_year'), ['reporting_year'], unique=False)
        batch_op.create_foreign_key('fk_submissions_reporting_period_id_reporting_periods', 'reporting_periods', ['reporting_period_id'], ['id'])

    # Backfill konservatif untuk data existing.
    # Default memakai tahun submitted_at, fallback created_at, fallback tahun berjalan DB.
    op.execute("""
        UPDATE submissions
        SET reporting_year = EXTRACT(
            YEAR FROM COALESCE(submitted_at, created_at, now())
        )::integer
        WHERE reporting_year IS NULL
    """)

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.alter_column('reporting_year', existing_type=sa.Integer(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_submissions_reporting_period_id_reporting_periods', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_submissions_reporting_year'))
        batch_op.drop_index(batch_op.f('ix_submissions_reporting_period_id'))
        batch_op.drop_column('reporting_period_id')
        batch_op.drop_column('reporting_year')

    with op.batch_alter_table('reporting_periods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reporting_periods_year'))
        batch_op.drop_index(batch_op.f('ix_reporting_periods_status'))
        batch_op.drop_index(batch_op.f('ix_reporting_periods_period_type'))
        batch_op.drop_index(batch_op.f('ix_reporting_periods_is_active'))
        batch_op.drop_index('ix_reporting_periods_deleted_at')

    op.drop_table('reporting_periods')
    # ### end Alembic commands ###
